name: Scheduled Trigger

on: 
  push:
    branches:
      - master
    paths:
      - '!list.json'
      - '!list_all.json'
      - '!list_raw.json'
  schedule: 
    - cron: '0 */1 * * *' # every hour
  
  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Node Package Install
      run: npm install
    
    - name: Node Run Code (index.js)
      run: node index.js
    
    - name: Deploy
      run: chmod +x deploy.sh && export token=${{ secrets.TOKEN }} username=${{secrets.USERNAME}} mail=${{secrets.MAIL}} name=${{secrets.NAME}} && ./deploy.sh
      env:
        CI: true
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BASE_BRANCH: master
        BRANCH: master
