name: Scheduled Trigger

on: 
  push:
    branches:
      - master
    paths:
      - '!list.json'
      - '!list_all.json'
      - '!list_raw.json'
  schedule: 
    - cron: '0 */1 * * *'
  
  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm i
      run: npm i
    
    - name: node index.js
      run: node index.js
    
    - name: Deploy
      run: chmod +x deploy.sh && export token=${{ secrets.TOKEN }} username=${{secrets.USERNAME}} mail=${{secrets.MAIL}} name=${{secrets.NAME}} && ./deploy.sh
      env:
        CI: true
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BASE_BRANCH: master
        BRANCH: master
