name: Push triggerer

on:
  push:
    branches:
      - master
    paths: 
      - '!list.json'
    #schedule: 
    #  - cron: '0 */1 * * *'

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm i
      run: cd listgen && npm i
    
    - name: node index.js
      run: cd listgen && node index.js
    
    - name: deploy
      run: cd listgen && chmod +x deploy.sh && export token=${{ secrets.TOKEN }} && export username=${{secrets.USERNAME}} && export mail=${{secrets.MAIL}} && export name=${{secrets.NAME}} && ./deploy.sh
      env:
        CI: true
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BASE_BRANCH: master
        BRANCH: master