name: Push triggerer

on:
  push:
    branches:
      - master
    paths: 
      - '!list.json'
      - '!list_all.json'
      - '!list_raw.json'
    #schedule: 
    #  - cron: '0 */1 * * *'

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch: # manually trigger a workflow run

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install & Run
      run: npm i && node index.js

    - name: Deploy
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        commit_message: "Update Data"
        file_pattern: "*.json"
